### ISSUE TITLE
是否包含 Dreamacro/clash 删库前的所有提交

### ISSUE THREAD

**Issue by chmod777john** [MysticalDevil/clash#1]
### 先决条件

- [X] 我了解这里是官方开源版 Clash 核心仓库，**只提供开源版或者 Premium 内核的支持**
- [X] 我要提交 Clash 核心的问题，并非 Clash.Meta / OpenClash / ClashX / Clash For Windows 或其他任何衍生版本的问题
- [X] 我使用的是**本仓库**最新版本的 Clash 或 Clash Premium 内核
- [X] 我已经在 [Issue Tracker](……/) 中找过我要提出的 bug，**并且没有找到相关问题**
- [X] 我已经仔细阅读 [官方 Wiki](https://dreamacro.github.io/clash/) 并无法自行解决问题
- [X] （非 Premium 内核必填）我已经使用 dev 分支版本测试过，问题依旧存在

### 版本

windows

### 适用的作业系统

Windows

### 配置文件

```YAML
无
```

### 日志输出

```Text
无
```

### 问题描述

`Dreamacro/clash` 已经删库，但是社区还有很多人想继续使用或者看代码，这样就需要找到一份 fork，包含尽量多删库前的提交。请问您的项目大致是什么时候克隆的呢，是否包含全部提交？

### 复现步骤

无

**Comment by askdaddy** [comment]
看commit 应该是9月份的

**Comment by MysticalDevil** [comment]
包含了全部的提交记录，最新的提交记录就是九月份的。这里有存好的快照
https://web.archive.org/web/20231102080948/https://github.com/Dreamacro/clash
